export const products = [
  {
    id: "p1",
    title: "Smartphone X100",
    price: 799.99,
    discount: 10,
    image: "https://placehold.co/600x400?text=Phone",
    rating: 4.5,
    category: "mobile",
    description: "A great phone",
  },
  {
    id: "p2",
    title: "Laptop Pro",
    price: 1299.99,
    discount: 15,
    image: "https://placehold.co/600x400?text=Laptop",
    rating: 4.7,
    category: "laptop",
    description: "Powerful laptop",
  },
  {
    id: "p3",
    title: "Wireless Headphones",
    price: 199.99,
    discount: 5,
    image: "https://placehold.co/600x400?text=Headphones",
    rating: 4.2,
    category: "mobile",
    description: "Noise-cancelling headphones",
  },
  {
    id: "p4",
    title: "Classic Jacket",
    price: 89.99,
    discount: 12,
    image: "https://placehold.co/600x400?text=Fashion",
    rating: 4.1,
    category: "fashion",
    description: "Everyday jacket",
  },
  {
    id: "p5",
    title: "Kids Toy Set",
    price: 39.99,
    discount: 8,
    image: "https://placehold.co/600x400?text=Kids",
    rating: 4.4,
    category: "kids",
    description: "Creative toy set",
  },
  {
    id: "p6",
    title: "Home Coffee Maker",
    price: 149.99,
    discount: 18,
    image: "https://placehold.co/600x400?text=Home",
    rating: 4.6,
    category: "home",
    description: "Compact coffee maker",
  },
];

