export const products = [
  {
    id: "p1",
    title: "Smartphone X100",
    price: 45000000,
    discount: 10,
    image: "/images/products/phone1.jpg",
    rating: 4.5,
    category: "mobile",
    description: "Modern smartphone",
  },
  {
    id: "p2",
    title: "Laptop Pro",
    price: 78000000,
    discount: 15,
    image: "/images/products/laptop1.jpg",
    rating: 4.7,
    category: "laptop",
    description: "Professional laptop",
  },
  {
    id: "p3",
    title: "Wireless Headphones",
    price: 8500000,
    discount: 5,
    image: "/images/products/headphones1.jpg",
    rating: 4.2,
    category: "mobile",
    description: "Noise cancelling",
  },
  {
    id: "p4",
    title: "Classic Jacket",
    price: 3200000,
    discount: 12,
    image: "/images/products/fashion1.jpg",
    rating: 4.1,
    category: "fashion",
    description: "Classic jacket",
  },
  {
    id: "p5",
    title: "Kids Toy Set",
    price: 1200000,
    discount: 8,
    image: "/images/products/kids1.jpg",
    rating: 4.4,
    category: "kids",
    description: "Fun toy set",
  },
  {
    id: "p6",
    title: "Coffee Maker",
    price: 6700000,
    discount: 18,
    image: "/images/products/home1.jpg",
    rating: 4.6,
    category: "home",
    description: "Coffee machine",
  },
  {
    id: "p7",
    title: "Gaming Mouse",
    price: 2500000,
    discount: 10,
    image: "/images/products/mouse.jpg",
    rating: 4.5,
    category: "laptop",
    description: "RGB mouse",
  },
  {
    id: "p8",
    title: "Smart Watch",
    price: 9800000,
    discount: 7,
    image: "/images/products/watch.jpg",
    rating: 4.8,
    category: "mobile",
    description: "Digital smartwatch",
  },
  {
    id: "p9",
    title: "Office Chair",
    price: 8900000,
    discount: 11,
    image: "/images/products/chair.jpg",
    rating: 4.3,
    category: "home",
    description: "Comfortable chair",
  },
  {
    id: "p10",
    title: "Kids Bicycle",
    price: 5400000,
    discount: 9,
    image: "/images/products/bike.jpg",
    rating: 4.4,
    category: "kids",
    description: "Kids bike",
  },
  {
    id: "p11",
    title: "Men Sneakers",
    price: 4100000,
    discount: 14,
    image: "/images/products/shoes.jpg",
    rating: 4.5,
    category: "fashion",
    description: "Sport shoes",
  },
  {
    id: "p12",
    title: "Bluetooth Speaker",
    price: 3700000,
    discount: 6,
    image: "/images/products/speaker.jpg",
    rating: 4.6,
    category: "mobile",
    description: "Portable speaker",
  },
  {
    id: "p13",
    title: "Tablet Air",
    price: 25000000,
    discount: 8,
    image: "/images/products/tablet.jpg",
    rating: 4.5,
    category: "mobile",
    description: "Slim tablet",
  },
  {
    id: "p14",
    title: "Mechanical Keyboard",
    price: 4900000,
    discount: 13,
    image: "/images/products/keyboard.jpg",
    rating: 4.7,
    category: "laptop",
    description: "Mechanical keyboard",
  },
  {
    id: "p15",
    title: "Gaming Monitor",
    price: 19500000,
    discount: 9,
    image: "/images/products/monitor.jpg",
    rating: 4.8,
    category: "laptop",
    description: "144Hz monitor",
  },
  {
    id: "p16",
    title: "Air Fryer",
    price: 7200000,
    discount: 17,
    image: "/images/products/airfryer.jpg",
    rating: 4.4,
    category: "home",
    description: "Healthy cooking",
  },
  {
    id: "p17",
    title: "Vacuum Cleaner",
    price: 11800000,
    discount: 10,
    image: "/images/products/vacuum.jpg",
    rating: 4.5,
    category: "home",
    description: "Powerful vacuum",
  },
  {
    id: "p18",
    title: "Women Handbag",
    price: 3600000,
    discount: 7,
    image: "/images/products/bag.jpg",
    rating: 4.3,
    category: "fashion",
    description: "Leather handbag",
  },
  {
    id: "p19",
    title: "Kids Puzzle",
    price: 950000,
    discount: 5,
    image: "/images/products/puzzle.jpg",
    rating: 4.2,
    category: "kids",
    description: "Educational puzzle",
  },
  {
    id: "p20",
    title: "LED TV 55",
    price: 34500000,
    discount: 12,
    image: "/images/products/tv.jpg",
    rating: 4.8,
    category: "home",
    description: "4K Smart TV",
  },
  {
    id: "p21",
    title: "Gaming Laptop",
    price: 95000000,
    discount: 10,
    image: "/images/products/gaminglaptop.jpg",
    rating: 4.9,
    category: "laptop",
    description: "Gaming laptop",
  },
  {
    id: "p22",
    title: "Fitness Band",
    price: 4200000,
    discount: 8,
    image: "/images/products/fitness.jpg",
    rating: 4.4,
    category: "mobile",
    description: "Fitness tracker",
  },
  {
    id: "p23",
    title: "Hair Dryer",
    price: 2300000,
    discount: 6,
    image: "/images/products/dryer.jpg",
    rating: 4.1,
    category: "home",
    description: "Hair dryer",
  },
  {
    id: "p24",
    title: "Winter Coat",
    price: 6900000,
    discount: 15,
    image: "/images/products/coat.jpg",
    rating: 4.6,
    category: "fashion",
    description: "Warm coat",
  },
  {
    id: "p25",
    title: "Toy Car",
    price: 750000,
    discount: 5,
    image: "/images/products/toycar.jpg",
    rating: 4.3,
    category: "kids",
    description: "Kids toy car",
  },
  {
    id: "p26",
    title: "Microwave Oven",
    price: 9600000,
    discount: 9,
    image: "/images/products/microwave.jpg",
    rating: 4.5,
    category: "home",
    description: "Microwave oven",
  },
  {
    id: "p27",
    title: "Smart Camera",
    price: 21500000,
    discount: 11,
    image: "/images/products/camera.jpg",
    rating: 4.7,
    category: "mobile",
    description: "HD camera",
  },
  {
    id: "p28",
    title: "Printer",
    price: 8300000,
    discount: 10,
    image: "/images/products/printer.jpg",
    rating: 4.3,
    category: "laptop",
    description: "Color printer",
  },
  {
    id: "p29",
    title: "Bluetooth Earbuds",
    price: 5600000,
    discount: 7,
    image: "/images/products/earbuds.jpg",
    rating: 4.5,
    category: "mobile",
    description: "Wireless earbuds",
  },
  {
    id: "p30",
    title: "Study Desk",
    price: 7800000,
    discount: 12,
    image: "/images/products/desk.jpg",
    rating: 4.2,
    category: "home",
    description: "Wooden desk",
  },
  {
    id: "p31",
    title: "Action Figure",
    price: 1100000,
    discount: 5,
    image: "/images/products/figure.jpg",
    rating: 4.4,
    category: "kids",
    description: "Superhero figure",
  },
  {
    id: "p32",
    title: "Running Shoes",
    price: 4700000,
    discount: 14,
    image: "/images/products/running.jpg",
    rating: 4.6,
    category: "fashion",
    description: "Running shoes",
  },
  {
    id: "p33",
    title: "External SSD",
    price: 6400000,
    discount: 9,
    image: "/images/products/ssd.jpg",
    rating: 4.8,
    category: "laptop",
    description: "Fast SSD",
  },
  {
    id: "p34",
    title: "Router WiFi 6",
    price: 5200000,
    discount: 8,
    image: "/images/products/router.jpg",
    rating: 4.5,
    category: "laptop",
    description: "High speed router",
  },
  {
    id: "p35",
    title: "Electric Kettle",
    price: 1900000,
    discount: 7,
    image: "/images/products/kettle.jpg",
    rating: 4.1,
    category: "home",
    description: "Fast boiling kettle",
  },
  {
    id: "p36",
    title: "Baby Stroller",
    price: 8800000,
    discount: 10,
    image: "/images/products/stroller.jpg",
    rating: 4.5,
    category: "kids",
    description: "Comfort stroller",
  },
  {
    id: "p37",
    title: "Perfume Luxury",
    price: 5300000,
    discount: 13,
    image: "/images/products/perfume.jpg",
    rating: 4.6,
    category: "fashion",
    description: "Luxury perfume",
  },
  {
    id: "p38",
    title: "Portable Charger",
    price: 2600000,
    discount: 6,
    image: "/images/products/powerbank.jpg",
    rating: 4.3,
    category: "mobile",
    description: "10000mAh powerbank",
  },
  {
    id: "p39",
    title: "Drone Mini",
    price: 28500000,
    discount: 10,
    image: "/images/products/drone.jpg",
    rating: 4.8,
    category: "mobile",
    description: "Camera drone",
  },
  {
    id: "p40",
    title: "Bookshelf",
    price: 4900000,
    discount: 9,
    image: "/images/products/bookshelf.jpg",
    rating: 4.2,
    category: "home",
    description: "Wood bookshelf",
  },
  {
    id: "p41",
    title: "Digital Clock",
    price: 1450000,
    discount: 5,
    image: "/images/products/clock.jpg",
    rating: 4.0,
    category: "home",
    description: "LED clock",
  },
  {
    id: "p42",
    title: "VR Headset",
    price: 24000000,
    discount: 12,
    image: "/images/products/vr.jpg",
    rating: 4.7,
    category: "mobile",
    description: "Virtual reality",
  },
  {
    id: "p43",
    title: "Leather Wallet",
    price: 1700000,
    discount: 8,
    image: "/images/products/wallet.jpg",
    rating: 4.3,
    category: "fashion",
    description: "Men wallet",
  },
  {
    id: "p44",
    title: "Toy Robot",
    price: 2100000,
    discount: 10,
    image: "/images/products/robot.jpg",
    rating: 4.5,
    category: "kids",
    description: "Robot toy",
  },
  {
    id: "p45",
    title: "Smart Lamp",
    price: 3400000,
    discount: 7,
    image: "/images/products/lamp.jpg",
    rating: 4.2,
    category: "home",
    description: "LED smart lamp",
  },
  {
    id: "p46",
    title: "Graphic Tablet",
    price: 12800000,
    discount: 11,
    image: "/images/products/graphictablet.jpg",
    rating: 4.6,
    category: "laptop",
    description: "Drawing tablet",
  },
  {
    id: "p47",
    title: "Wireless Charger",
    price: 1800000,
    discount: 6,
    image: "/images/products/charger.jpg",
    rating: 4.1,
    category: "mobile",
    description: "Fast charger",
  },
  {
    id: "p48",
    title: "Travel Bag",
    price: 3900000,
    discount: 9,
    image: "/images/products/travelbag.jpg",
    rating: 4.4,
    category: "fashion",
    description: "Large travel bag",
  },
  {
    id: "p49",
    title: "Toy Train",
    price: 1350000,
    discount: 5,
    image: "/images/products/train.jpg",
    rating: 4.3,
    category: "kids",
    description: "Electric train toy",
  },
  {
    id: "p50",
    title: "Portable Projector",
    price: 15800000,
    discount: 13,
    image: "/images/products/projector.jpg",
    rating: 4.7,
    category: "home",
    description: "Mini projector",
  },
];
